/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as FuncRouteImport } from './routes/_func'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FuncionarioLoginRouteImport } from './routes/funcionario.login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCadastroRouteImport } from './routes/admin.cadastro'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as FuncFuncionarioResumoRouteImport } from './routes/_func.funcionario.resumo'
import { Route as FuncFuncionarioPerfilRouteImport } from './routes/_func.funcionario.perfil'
import { Route as FuncFuncionarioMeuPontoRouteImport } from './routes/_func.funcionario.meu-ponto'
import { Route as FuncFuncionarioHistoricoRouteImport } from './routes/_func.funcionario.historico'
import { Route as AdminAdminRelatoriosRouteImport } from './routes/_admin.admin.relatorios'
import { Route as AdminAdminPontosRouteImport } from './routes/_admin.admin.pontos'
import { Route as AdminAdminFuncionariosRouteImport } from './routes/_admin.admin.funcionarios'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as AdminAdminConfiguracoesRouteImport } from './routes/_admin.admin.configuracoes'
import { Route as AdminAdminAssinaturaRouteImport } from './routes/_admin.admin.assinatura'
import { Route as AdminAdminAbonosRouteImport } from './routes/_admin.admin.abonos'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncRoute = FuncRouteImport.update({
  id: '/_func',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionarioLoginRoute = FuncionarioLoginRouteImport.update({
  id: '/funcionario/login',
  path: '/funcionario/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCadastroRoute = AdminCadastroRouteImport.update({
  id: '/admin/cadastro',
  path: '/admin/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncFuncionarioResumoRoute = FuncFuncionarioResumoRouteImport.update({
  id: '/funcionario/resumo',
  path: '/funcionario/resumo',
  getParentRoute: () => FuncRoute,
} as any)
const FuncFuncionarioPerfilRoute = FuncFuncionarioPerfilRouteImport.update({
  id: '/funcionario/perfil',
  path: '/funcionario/perfil',
  getParentRoute: () => FuncRoute,
} as any)
const FuncFuncionarioMeuPontoRoute = FuncFuncionarioMeuPontoRouteImport.update({
  id: '/funcionario/meu-ponto',
  path: '/funcionario/meu-ponto',
  getParentRoute: () => FuncRoute,
} as any)
const FuncFuncionarioHistoricoRoute =
  FuncFuncionarioHistoricoRouteImport.update({
    id: '/funcionario/historico',
    path: '/funcionario/historico',
    getParentRoute: () => FuncRoute,
  } as any)
const AdminAdminRelatoriosRoute = AdminAdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPontosRoute = AdminAdminPontosRouteImport.update({
  id: '/admin/pontos',
  path: '/admin/pontos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFuncionariosRoute = AdminAdminFuncionariosRouteImport.update({
  id: '/admin/funcionarios',
  path: '/admin/funcionarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminConfiguracoesRoute = AdminAdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAssinaturaRoute = AdminAdminAssinaturaRouteImport.update({
  id: '/admin/assinatura',
  path: '/admin/assinatura',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAbonosRoute = AdminAdminAbonosRouteImport.update({
  id: '/admin/abonos',
  path: '/admin/abonos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/funcionario/login': typeof FuncionarioLoginRoute
  '/admin/abonos': typeof AdminAdminAbonosRoute
  '/admin/assinatura': typeof AdminAdminAssinaturaRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/funcionarios': typeof AdminAdminFuncionariosRoute
  '/admin/pontos': typeof AdminAdminPontosRoute
  '/admin/relatorios': typeof AdminAdminRelatoriosRoute
  '/funcionario/historico': typeof FuncFuncionarioHistoricoRoute
  '/funcionario/meu-ponto': typeof FuncFuncionarioMeuPontoRoute
  '/funcionario/perfil': typeof FuncFuncionarioPerfilRoute
  '/funcionario/resumo': typeof FuncFuncionarioResumoRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/funcionario/login': typeof FuncionarioLoginRoute
  '/admin/abonos': typeof AdminAdminAbonosRoute
  '/admin/assinatura': typeof AdminAdminAssinaturaRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/funcionarios': typeof AdminAdminFuncionariosRoute
  '/admin/pontos': typeof AdminAdminPontosRoute
  '/admin/relatorios': typeof AdminAdminRelatoriosRoute
  '/funcionario/historico': typeof FuncFuncionarioHistoricoRoute
  '/funcionario/meu-ponto': typeof FuncFuncionarioMeuPontoRoute
  '/funcionario/perfil': typeof FuncFuncionarioPerfilRoute
  '/funcionario/resumo': typeof FuncFuncionarioResumoRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_func': typeof FuncRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/funcionario/login': typeof FuncionarioLoginRoute
  '/_admin/admin/abonos': typeof AdminAdminAbonosRoute
  '/_admin/admin/assinatura': typeof AdminAdminAssinaturaRoute
  '/_admin/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/funcionarios': typeof AdminAdminFuncionariosRoute
  '/_admin/admin/pontos': typeof AdminAdminPontosRoute
  '/_admin/admin/relatorios': typeof AdminAdminRelatoriosRoute
  '/_func/funcionario/historico': typeof FuncFuncionarioHistoricoRoute
  '/_func/funcionario/meu-ponto': typeof FuncFuncionarioMeuPontoRoute
  '/_func/funcionario/perfil': typeof FuncFuncionarioPerfilRoute
  '/_func/funcionario/resumo': typeof FuncFuncionarioResumoRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacidade'
    | '/termos'
    | '/admin/cadastro'
    | '/admin/login'
    | '/auth/reset-password'
    | '/funcionario/login'
    | '/admin/abonos'
    | '/admin/assinatura'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/funcionarios'
    | '/admin/pontos'
    | '/admin/relatorios'
    | '/funcionario/historico'
    | '/funcionario/meu-ponto'
    | '/funcionario/perfil'
    | '/funcionario/resumo'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidade'
    | '/termos'
    | '/admin/cadastro'
    | '/admin/login'
    | '/auth/reset-password'
    | '/funcionario/login'
    | '/admin/abonos'
    | '/admin/assinatura'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/funcionarios'
    | '/admin/pontos'
    | '/admin/relatorios'
    | '/funcionario/historico'
    | '/funcionario/meu-ponto'
    | '/funcionario/perfil'
    | '/funcionario/resumo'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_func'
    | '/privacidade'
    | '/termos'
    | '/admin/cadastro'
    | '/admin/login'
    | '/auth/reset-password'
    | '/funcionario/login'
    | '/_admin/admin/abonos'
    | '/_admin/admin/assinatura'
    | '/_admin/admin/configuracoes'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/funcionarios'
    | '/_admin/admin/pontos'
    | '/_admin/admin/relatorios'
    | '/_func/funcionario/historico'
    | '/_func/funcionario/meu-ponto'
    | '/_func/funcionario/perfil'
    | '/_func/funcionario/resumo'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FuncRoute: typeof FuncRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AdminCadastroRoute: typeof AdminCadastroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  FuncionarioLoginRoute: typeof FuncionarioLoginRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_func': {
      id: '/_func'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FuncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionario/login': {
      id: '/funcionario/login'
      path: '/funcionario/login'
      fullPath: '/funcionario/login'
      preLoaderRoute: typeof FuncionarioLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cadastro': {
      id: '/admin/cadastro'
      path: '/admin/cadastro'
      fullPath: '/admin/cadastro'
      preLoaderRoute: typeof AdminCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_func/funcionario/resumo': {
      id: '/_func/funcionario/resumo'
      path: '/funcionario/resumo'
      fullPath: '/funcionario/resumo'
      preLoaderRoute: typeof FuncFuncionarioResumoRouteImport
      parentRoute: typeof FuncRoute
    }
    '/_func/funcionario/perfil': {
      id: '/_func/funcionario/perfil'
      path: '/funcionario/perfil'
      fullPath: '/funcionario/perfil'
      preLoaderRoute: typeof FuncFuncionarioPerfilRouteImport
      parentRoute: typeof FuncRoute
    }
    '/_func/funcionario/meu-ponto': {
      id: '/_func/funcionario/meu-ponto'
      path: '/funcionario/meu-ponto'
      fullPath: '/funcionario/meu-ponto'
      preLoaderRoute: typeof FuncFuncionarioMeuPontoRouteImport
      parentRoute: typeof FuncRoute
    }
    '/_func/funcionario/historico': {
      id: '/_func/funcionario/historico'
      path: '/funcionario/historico'
      fullPath: '/funcionario/historico'
      preLoaderRoute: typeof FuncFuncionarioHistoricoRouteImport
      parentRoute: typeof FuncRoute
    }
    '/_admin/admin/relatorios': {
      id: '/_admin/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminAdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pontos': {
      id: '/_admin/admin/pontos'
      path: '/admin/pontos'
      fullPath: '/admin/pontos'
      preLoaderRoute: typeof AdminAdminPontosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/funcionarios': {
      id: '/_admin/admin/funcionarios'
      path: '/admin/funcionarios'
      fullPath: '/admin/funcionarios'
      preLoaderRoute: typeof AdminAdminFuncionariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/configuracoes': {
      id: '/_admin/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/assinatura': {
      id: '/_admin/admin/assinatura'
      path: '/admin/assinatura'
      fullPath: '/admin/assinatura'
      preLoaderRoute: typeof AdminAdminAssinaturaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/abonos': {
      id: '/_admin/admin/abonos'
      path: '/admin/abonos'
      fullPath: '/admin/abonos'
      preLoaderRoute: typeof AdminAdminAbonosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAbonosRoute: typeof AdminAdminAbonosRoute
  AdminAdminAssinaturaRoute: typeof AdminAdminAssinaturaRoute
  AdminAdminConfiguracoesRoute: typeof AdminAdminConfiguracoesRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminFuncionariosRoute: typeof AdminAdminFuncionariosRoute
  AdminAdminPontosRoute: typeof AdminAdminPontosRoute
  AdminAdminRelatoriosRoute: typeof AdminAdminRelatoriosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAbonosRoute: AdminAdminAbonosRoute,
  AdminAdminAssinaturaRoute: AdminAdminAssinaturaRoute,
  AdminAdminConfiguracoesRoute: AdminAdminConfiguracoesRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminFuncionariosRoute: AdminAdminFuncionariosRoute,
  AdminAdminPontosRoute: AdminAdminPontosRoute,
  AdminAdminRelatoriosRoute: AdminAdminRelatoriosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FuncRouteChildren {
  FuncFuncionarioHistoricoRoute: typeof FuncFuncionarioHistoricoRoute
  FuncFuncionarioMeuPontoRoute: typeof FuncFuncionarioMeuPontoRoute
  FuncFuncionarioPerfilRoute: typeof FuncFuncionarioPerfilRoute
  FuncFuncionarioResumoRoute: typeof FuncFuncionarioResumoRoute
}

const FuncRouteChildren: FuncRouteChildren = {
  FuncFuncionarioHistoricoRoute: FuncFuncionarioHistoricoRoute,
  FuncFuncionarioMeuPontoRoute: FuncFuncionarioMeuPontoRoute,
  FuncFuncionarioPerfilRoute: FuncFuncionarioPerfilRoute,
  FuncFuncionarioResumoRoute: FuncFuncionarioResumoRoute,
}

const FuncRouteWithChildren = FuncRoute._addFileChildren(FuncRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FuncRoute: FuncRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AdminCadastroRoute: AdminCadastroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  FuncionarioLoginRoute: FuncionarioLoginRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
