/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FuncRouteImport } from './routes/_func'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FuncionarioLoginRouteImport } from './routes/funcionario.login'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCadastroRouteImport } from './routes/admin.cadastro'
import { Route as FuncFuncionarioMeuPontoRouteImport } from './routes/_func.funcionario.meu-ponto'
import { Route as FuncFuncionarioHistoricoRouteImport } from './routes/_func.funcionario.historico'
import { Route as AdminAdminPontosRouteImport } from './routes/_admin.admin.pontos'
import { Route as AdminAdminFuncionariosRouteImport } from './routes/_admin.admin.funcionarios'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as AdminAdminConfiguracoesRouteImport } from './routes/_admin.admin.configuracoes'

const FuncRoute = FuncRouteImport.update({
  id: '/_func',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionarioLoginRoute = FuncionarioLoginRouteImport.update({
  id: '/funcionario/login',
  path: '/funcionario/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCadastroRoute = AdminCadastroRouteImport.update({
  id: '/admin/cadastro',
  path: '/admin/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncFuncionarioMeuPontoRoute = FuncFuncionarioMeuPontoRouteImport.update({
  id: '/funcionario/meu-ponto',
  path: '/funcionario/meu-ponto',
  getParentRoute: () => FuncRoute,
} as any)
const FuncFuncionarioHistoricoRoute =
  FuncFuncionarioHistoricoRouteImport.update({
    id: '/funcionario/historico',
    path: '/funcionario/historico',
    getParentRoute: () => FuncRoute,
  } as any)
const AdminAdminPontosRoute = AdminAdminPontosRouteImport.update({
  id: '/admin/pontos',
  path: '/admin/pontos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFuncionariosRoute = AdminAdminFuncionariosRouteImport.update({
  id: '/admin/funcionarios',
  path: '/admin/funcionarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminConfiguracoesRoute = AdminAdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/login': typeof AdminLoginRoute
  '/funcionario/login': typeof FuncionarioLoginRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/funcionarios': typeof AdminAdminFuncionariosRoute
  '/admin/pontos': typeof AdminAdminPontosRoute
  '/funcionario/historico': typeof FuncFuncionarioHistoricoRoute
  '/funcionario/meu-ponto': typeof FuncFuncionarioMeuPontoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/login': typeof AdminLoginRoute
  '/funcionario/login': typeof FuncionarioLoginRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/funcionarios': typeof AdminAdminFuncionariosRoute
  '/admin/pontos': typeof AdminAdminPontosRoute
  '/funcionario/historico': typeof FuncFuncionarioHistoricoRoute
  '/funcionario/meu-ponto': typeof FuncFuncionarioMeuPontoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_func': typeof FuncRouteWithChildren
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/login': typeof AdminLoginRoute
  '/funcionario/login': typeof FuncionarioLoginRoute
  '/_admin/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/funcionarios': typeof AdminAdminFuncionariosRoute
  '/_admin/admin/pontos': typeof AdminAdminPontosRoute
  '/_func/funcionario/historico': typeof FuncFuncionarioHistoricoRoute
  '/_func/funcionario/meu-ponto': typeof FuncFuncionarioMeuPontoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/cadastro'
    | '/admin/login'
    | '/funcionario/login'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/funcionarios'
    | '/admin/pontos'
    | '/funcionario/historico'
    | '/funcionario/meu-ponto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/cadastro'
    | '/admin/login'
    | '/funcionario/login'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/funcionarios'
    | '/admin/pontos'
    | '/funcionario/historico'
    | '/funcionario/meu-ponto'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_func'
    | '/admin/cadastro'
    | '/admin/login'
    | '/funcionario/login'
    | '/_admin/admin/configuracoes'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/funcionarios'
    | '/_admin/admin/pontos'
    | '/_func/funcionario/historico'
    | '/_func/funcionario/meu-ponto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FuncRoute: typeof FuncRouteWithChildren
  AdminCadastroRoute: typeof AdminCadastroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  FuncionarioLoginRoute: typeof FuncionarioLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_func': {
      id: '/_func'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FuncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionario/login': {
      id: '/funcionario/login'
      path: '/funcionario/login'
      fullPath: '/funcionario/login'
      preLoaderRoute: typeof FuncionarioLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cadastro': {
      id: '/admin/cadastro'
      path: '/admin/cadastro'
      fullPath: '/admin/cadastro'
      preLoaderRoute: typeof AdminCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_func/funcionario/meu-ponto': {
      id: '/_func/funcionario/meu-ponto'
      path: '/funcionario/meu-ponto'
      fullPath: '/funcionario/meu-ponto'
      preLoaderRoute: typeof FuncFuncionarioMeuPontoRouteImport
      parentRoute: typeof FuncRoute
    }
    '/_func/funcionario/historico': {
      id: '/_func/funcionario/historico'
      path: '/funcionario/historico'
      fullPath: '/funcionario/historico'
      preLoaderRoute: typeof FuncFuncionarioHistoricoRouteImport
      parentRoute: typeof FuncRoute
    }
    '/_admin/admin/pontos': {
      id: '/_admin/admin/pontos'
      path: '/admin/pontos'
      fullPath: '/admin/pontos'
      preLoaderRoute: typeof AdminAdminPontosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/funcionarios': {
      id: '/_admin/admin/funcionarios'
      path: '/admin/funcionarios'
      fullPath: '/admin/funcionarios'
      preLoaderRoute: typeof AdminAdminFuncionariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/configuracoes': {
      id: '/_admin/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminConfiguracoesRoute: typeof AdminAdminConfiguracoesRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminFuncionariosRoute: typeof AdminAdminFuncionariosRoute
  AdminAdminPontosRoute: typeof AdminAdminPontosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminConfiguracoesRoute: AdminAdminConfiguracoesRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminFuncionariosRoute: AdminAdminFuncionariosRoute,
  AdminAdminPontosRoute: AdminAdminPontosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FuncRouteChildren {
  FuncFuncionarioHistoricoRoute: typeof FuncFuncionarioHistoricoRoute
  FuncFuncionarioMeuPontoRoute: typeof FuncFuncionarioMeuPontoRoute
}

const FuncRouteChildren: FuncRouteChildren = {
  FuncFuncionarioHistoricoRoute: FuncFuncionarioHistoricoRoute,
  FuncFuncionarioMeuPontoRoute: FuncFuncionarioMeuPontoRoute,
}

const FuncRouteWithChildren = FuncRoute._addFileChildren(FuncRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FuncRoute: FuncRouteWithChildren,
  AdminCadastroRoute: AdminCadastroRoute,
  AdminLoginRoute: AdminLoginRoute,
  FuncionarioLoginRoute: FuncionarioLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
